SWEETS = [{"ID":92847591,"Name":"Astros","Manufacturer":"Cadburry","Country":"South Africa","Kind":"Chocolate"},
{"ID":93847582,"Name":"Pocky","Manufacturer":"Ezaki Glico","Country":"Japan","Kind":"Chocolate Covered Buscuit Sticks"},
{"ID":18273846,"Name":"Pez","Manufacturer":"Haas","Country":"Austria","Kind":"Hard Candy"},
{"ID":53928475,"Name":"Hollywood","Manufacturer":"Cadburry","Country":"France","Kind":"Chocolate"},
{"ID":73847596,"Name":"Milka","Manufacturer":"Kraft","Country":"Germany","Kind":"Chocolate"},
{"ID":42937485,"Name":"Gummi Worms","Manufacturer":"Trolli","Country":"Germany","Kind":"Chewy Candy"},
{"ID":88236475,"Name":"Saladitos","Manufacturer":"De La Rosa","Country":"Mexico","Kind":"Dried Plums"},
{"ID":92838475,"Name":"Almond Joy","Manufacturer":"Hershey","Country":"United States","Kind":"Chocolate"},
{"ID":10292637,"Name":"Trident","Manufacturer":"Cadburry","Country":"Brazil","Kind":"Gum"},
{"ID":77283647,"Name":"Snickers","Manufacturer":"Mars","Country":"United States","Kind":"Chocolate"},
{"ID":61919287,"Name":"M&Ms","Manufacturer":"Mars","Country":"United States","Kind":"Chocolate"},
{"ID":99283748,"Name":"Tootsie Roll","Manufacturer":"Tootsie Roll Industries","Country":"United States","Kind":"Toffee"},
{"ID":23716274,"Name":"Crunky","Manufacturer":"Lotte","Country":"South Korea","Kind":"Chocolate"},
{"ID":92837948,"Name":"Balisto","Manufacturer":"Germandeli","Country":"Italy","Kind":"Chocolate"},
{"ID":18292437,"Name":"Gummy Bears","Manufacturer":"Haribo","Country":"Germany","Kind":"Chewy Candy"},
{"ID":99283742,"Name":"Plopp","Manufacturer":"Cloetta","Country":"Sweden","Kind":"Chocolate"},
{"ID":22928374,"Name":"Kinder Surprise ","Manufacturer":"Kinder","Country":"Germany","Kind":"Chocolate "},
{"ID":22839478,"Name":"Galaxy","Manufacturer":"Mars","Country":"Saudi Arabia","Kind":"Chocolate"},
{"ID":73293849,"Name":"Turkish Delight","Manufacturer":"Liberty Orchards","Country":"Turkey","Kind":"Chewy Candy"},
{"ID":18374892,"Name":"WunderBar","Manufacturer":"Cadburry","Country":"Canada","Kind":"Chocolate"}];
